- name: Sample
  hosts: localhost
  tasks:

      - name: This is a Sample from the service
        service:
          name: '{{ item }}'
          state: started
        with_items:
            - docker
            - firewalld
