- name: Sample_docker
  hosts: web_servers
  become: yes
  tasks:

      - name: This is a Sample from the service
        service:
          name: '{{ item }}'
          state: started
        with_items:
            - docker
            - firewalld
